Add `vtk.js` to Atlascope
atlascope/atlascope pull request #196
Opened 2022-07-22 18:17 UTC by naglepuff

2022-08-11 14:46 UTC, annehaley requested changes

2022-08-11 14:46 UTC, annehaley commented on atlascope/core/management/commands/populate.py
> +        # datasets = [dataset for dataset in datasets if dataset.content]
This addition can be left out

2022-08-11 14:46 UTC, annehaley commented on web/src/components/InvestigationSidebar.vue
> +      </v-tab-item>
Are we going to offer either vtk.js OR paraview glance to visualize 3d data?

2022-08-11 14:46 UTC, annehaley commented on web/src/views/InvestigationDetail.vue
> +    }
I am a bit confused about when we open something in glance vs vtk.js

2022-08-15 17:59 UTC, naglepuff commented
Closing in favor of #200. This could be cool to come back to at some point if we want to add multiple visualization options. At this point in the project, #200 does a good job of showing how we can integrate other tools or services to allow for interacting with Atlascope data.

2022-08-15 17:59 UTC, closed without merging