Job result vis improvements
atlascope/atlascope pull request #209
Opened 2022-08-18 15:26 UTC by annehaley

This PR is the clean version of #201 and #204, where git rebasing and diverging branches made the history messy.

This PR accomplishes the following:

- Separate the logic for turning on job result visualizations from the logic for turning on pin visibility
- Offer options for job result visualizations as checkboxes that appear when the parent checkbox is active
- Add an option to color nuclei centroids by the nearest gland, resulting in something similar to a voronoi diagram

2022-08-18 21:08 UTC, naglepuff requested changes
Most of these are continuations from #204.

2022-08-18 21:08 UTC, naglepuff commented on web/package.json
> +    "distinct-colors": "^3.0.0",
I think @mcovalt is also doing some color-coding stuff in PR #208. Might be worth coordinating what package to use here. I know D3 came up in one of our discussions.

2022-08-18 21:08 UTC, naglepuff commented on web/src/components/JobVisOptions.vue
> +      type: Object,
To continue our discussion from #204, you can do `type: Object as () => Pin`. I think this will be enough for the typescript linter to be able to infer `props.pin`.

2022-08-18 21:08 UTC, naglepuff commented on web/src/components/JobVisOptions.vue
> +      @click="(event) => event.stopPropagation()"
From the conversation on #204, it sounds like `@click.stop=""` doesn't work. 

I'm also curious as to why something like this would need to be added at all to the `<div>` element. Is the problem that the event is bubbling up from child elements? What if you added the `.stop` modifier to the `change` events on the children elements?

2022-08-18 21:08 UTC, naglepuff commented on web/src/generatedTypes/AtlascopeTypes.ts
> +}
Can you re-run `generateTypes`? I see you moved this to `utilities/visualizationTypes.ts`.

2022-08-19 12:53 UTC, waxlamp commented on web/package.json
> +    "distinct-colors": "^3.0.0",
Check out https://github.com/d3/d3-scale-chromatic. This `distinct-colors` library seems neat, but when we're doing any kind of color picking for visualizing, my gut tells me you're better off with the prebaked thought that has gone into D3.

2022-08-22 12:39 UTC, annehaley commented on web/src/components/JobVisOptions.vue
> +      @click="(event) => event.stopPropagation()"
I tried removing line 17 and changing 22 to `@change.stop="() => updateVisualizationsShown(visOption)"`, as well as 35 to  `@change.stop="() => updateOption(visOption, available.value)"`. But it results in the following behavior:

https://user-images.githubusercontent.com/44912689/185922950-dbf57d02-36f9-4ae5-8227-62862cf6cda8.mov

It seems that the propagation stop has to belong to the direct child of the checkbox content, which is the div in this case. Else the checkbox will interpret that click as a toggle.

2022-08-22 13:24 UTC, annehaley commented on web/package.json
> +    "distinct-colors": "^3.0.0",
Ok, I added d3  in [2321cb8](https://github.com/atlascope/atlascope/pull/209/commits/2321cb86ea267fe32e47cfe0ecdcb34c0020d01e) and used schemeCategory10. It doesn't seem to have a scheme with 20 distinct colors, but I suppose it's expected that the colors will loop. With 20 glands present (and therefore 20 color groups), the centroids look like this: 
![image](https://user-images.githubusercontent.com/44912689/185931497-a3884474-102f-45a6-9897-30a4d1fc88bc.png)
Is this good or should I use a different scheme?

2022-08-22 13:26 UTC, annehaley commented on web/src/components/JobVisOptions.vue
> +      type: Object,
Nice, I didn't know you could do that. Changed in [edb7bac](https://github.com/atlascope/atlascope/pull/209/commits/edb7bac8abe7d88d0890b1fce959ff5902e9ce26).

2022-08-22 13:28 UTC, annehaley commented on web/src/generatedTypes/AtlascopeTypes.ts
> +}
Re-generated in [9c45863](https://github.com/atlascope/atlascope/pull/209/commits/9c45863083683d7c957d8e0d837391b07bef0b79)

2022-08-22 14:36 UTC, waxlamp commented on web/package.json
> +    "distinct-colors": "^3.0.0",
D3 used to have a `category20` colormap that contained these 10 colors plus darker versions of the same, but it kooks like they got rid of it. But this is a problem inherent to categorical colormapping, that you don't have more than just a handful of colors before you need to repeat. That's fine, especially in this case. (If you try to manufacture your own set of distinct colors, you'll run into the same ultimate problem anyway, of different categories being served by visually close colors.)

2022-08-22 15:14 UTC, naglepuff commented on web/src/components/JobVisOptions.vue
> +      @click="(event) => event.stopPropagation()"
Hmm, that's interesting. Thanks for testing it out

2022-08-22 15:35 UTC, naglepuff approved these changes
LGTM. Something to consider for a follow up would be to make the glands more visually distinct from the nuclei (larger radius, add a border, etc).

2022-08-22 15:57 UTC, merged